### PR TITLE
Fix dot call false positive

### LINKED ISSUE #33: The pattern %{tag_name: _gen} on line X doesn't have the type acc()
This is my project and commit
https://github.com/eksperimental/beam_langs_meta_data/tree/26ecd958475bedd5c0e4204814e7437484acdff4

> lib/beam_langs_meta_data/util.ex: The pattern %{tag_name: _gen} on line 178 doesn't have the type acc()

I am unable to understand this error and what needs to be fixed.

### PR DESCRIPTION
**Pull request by erszcz**
This fixes #33.

### CODE REVIEW

File: lib/gradient/elixir_syntax.ex [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+         {:type_error, :pattern, _,
+          {:map, _,
+           [
+             {:map_field_exact, _, {:atom, fun_anno, _function_name},
+              {:var, _var_anno, _var_name}}
+           ]}, _called_expr_type}}
+      ) do
+    ## Ideally, we would also check for `generated: true` in `_var_anno`, but Elixir 1.11 doesn't
+    ## set it, whereas the error shape is exactly the same so we cannot add another match
+    ## in the function head.
```
Comment (Premwoik) [inline lib/gradient/elixir_syntax.ex:58]: Maybe we should use `System.version` and add this check only for the latest versions?

**Review by Premwoik — APPROVED** [review]
Looks good 👏

File: lib/gradient/elixir_syntax.ex (hunk 1 above)
Comment (erszcz) [reply lib/gradient/elixir_syntax.ex:58]: Hmm, might be a good idea for later.
